webtalk_init -webtalk_dir C:/Users/LENOVO/Desktop/DDA/verilog_tests/compuertas/compuertas/compuertas.sim/sim_1/behav/xsim/xsim.dir/compuertasLogicas_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Sep 19 19:57:16 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "881c8dab-4f59-474b-8653-1c5b85aa92c6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d1d64c8189ab4b04857e5ab50d135fa6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2803 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6708_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1352879163 -regid "" -xml C:/Users/LENOVO/Desktop/DDA/verilog_tests/compuertas/compuertas/compuertas.sim/sim_1/behav/xsim/xsim.dir/compuertasLogicas_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/LENOVO/Desktop/DDA/verilog_tests/compuertas/compuertas/compuertas.sim/sim_1/behav/xsim/xsim.dir/compuertasLogicas_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/LENOVO/Desktop/DDA/verilog_tests/compuertas/compuertas/compuertas.sim/sim_1/behav/xsim/xsim.dir/compuertasLogicas_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
